#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/FireAlarmConfigTool.Logic.Api/ && \
    dotnet build src/FireAlarmConfigTool.Logic.Api/ && \
    echo "Now, run the following to start the project: dotnet run -p src/FireAlarmConfigTool.Logic.Api/FireAlarmConfigTool.Logic.Api.csproj --launch-profile web"
