:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\FireAlarmConfigTool.Logic.Api
dotnet build src\FireAlarmConfigTool.Logic.Api
echo Now, run the following to start the project: dotnet run -p src\FireAlarmConfigTool.Logic.Api\FireAlarmConfigTool.Logic.Api.csproj --launch-profile web.
echo.
