/*
 * Fire Alarm Config Tool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using FireAlarmConfigTool.Logic.Http.Client.Client;

namespace FireAlarmConfigTool.Logic.Http.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Test endpoint
        /// </summary>
        /// <remarks>
        /// Returns a greeting that includes the provided number.
        /// </remarks>
        /// <exception cref="FireAlarmConfigTool.Logic.Http.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="num">A number to include in the greeting</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>string</returns>
        string TestGet(int num, int operationIndex = 0);

        /// <summary>
        /// Test endpoint
        /// </summary>
        /// <remarks>
        /// Returns a greeting that includes the provided number.
        /// </remarks>
        /// <exception cref="FireAlarmConfigTool.Logic.Http.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="num">A number to include in the greeting</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> TestGetWithHttpInfo(int num, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Test endpoint
        /// </summary>
        /// <remarks>
        /// Returns a greeting that includes the provided number.
        /// </remarks>
        /// <exception cref="FireAlarmConfigTool.Logic.Http.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="num">A number to include in the greeting</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> TestGetAsync(int num, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Test endpoint
        /// </summary>
        /// <remarks>
        /// Returns a greeting that includes the provided number.
        /// </remarks>
        /// <exception cref="FireAlarmConfigTool.Logic.Http.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="num">A number to include in the greeting</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> TestGetWithHttpInfoAsync(int num, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApi : IDefaultApiSync, IDefaultApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DefaultApi : IDefaultApi
    {
        private FireAlarmConfigTool.Logic.Http.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DefaultApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DefaultApi(string basePath)
        {
            this.Configuration = FireAlarmConfigTool.Logic.Http.Client.Client.Configuration.MergeConfigurations(
                FireAlarmConfigTool.Logic.Http.Client.Client.GlobalConfiguration.Instance,
                new FireAlarmConfigTool.Logic.Http.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new FireAlarmConfigTool.Logic.Http.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new FireAlarmConfigTool.Logic.Http.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = FireAlarmConfigTool.Logic.Http.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DefaultApi(FireAlarmConfigTool.Logic.Http.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = FireAlarmConfigTool.Logic.Http.Client.Client.Configuration.MergeConfigurations(
                FireAlarmConfigTool.Logic.Http.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new FireAlarmConfigTool.Logic.Http.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new FireAlarmConfigTool.Logic.Http.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = FireAlarmConfigTool.Logic.Http.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DefaultApi(FireAlarmConfigTool.Logic.Http.Client.Client.ISynchronousClient client, FireAlarmConfigTool.Logic.Http.Client.Client.IAsynchronousClient asyncClient, FireAlarmConfigTool.Logic.Http.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = FireAlarmConfigTool.Logic.Http.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public FireAlarmConfigTool.Logic.Http.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public FireAlarmConfigTool.Logic.Http.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public FireAlarmConfigTool.Logic.Http.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public FireAlarmConfigTool.Logic.Http.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Test endpoint Returns a greeting that includes the provided number.
        /// </summary>
        /// <exception cref="FireAlarmConfigTool.Logic.Http.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="num">A number to include in the greeting</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>string</returns>
        public string TestGet(int num, int operationIndex = 0)
        {
            FireAlarmConfigTool.Logic.Http.Client.Client.ApiResponse<string> localVarResponse = TestGetWithHttpInfo(num);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Test endpoint Returns a greeting that includes the provided number.
        /// </summary>
        /// <exception cref="FireAlarmConfigTool.Logic.Http.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="num">A number to include in the greeting</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of string</returns>
        public FireAlarmConfigTool.Logic.Http.Client.Client.ApiResponse<string> TestGetWithHttpInfo(int num, int operationIndex = 0)
        {
            FireAlarmConfigTool.Logic.Http.Client.Client.RequestOptions localVarRequestOptions = new FireAlarmConfigTool.Logic.Http.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = FireAlarmConfigTool.Logic.Http.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = FireAlarmConfigTool.Logic.Http.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(FireAlarmConfigTool.Logic.Http.Client.Client.ClientUtils.ParameterToMultiMap("", "num", num));

            localVarRequestOptions.Operation = "DefaultApi.TestGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<string>("/test", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("TestGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Test endpoint Returns a greeting that includes the provided number.
        /// </summary>
        /// <exception cref="FireAlarmConfigTool.Logic.Http.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="num">A number to include in the greeting</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> TestGetAsync(int num, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            FireAlarmConfigTool.Logic.Http.Client.Client.ApiResponse<string> localVarResponse = await TestGetWithHttpInfoAsync(num, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Test endpoint Returns a greeting that includes the provided number.
        /// </summary>
        /// <exception cref="FireAlarmConfigTool.Logic.Http.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="num">A number to include in the greeting</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<FireAlarmConfigTool.Logic.Http.Client.Client.ApiResponse<string>> TestGetWithHttpInfoAsync(int num, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            FireAlarmConfigTool.Logic.Http.Client.Client.RequestOptions localVarRequestOptions = new FireAlarmConfigTool.Logic.Http.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = FireAlarmConfigTool.Logic.Http.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = FireAlarmConfigTool.Logic.Http.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(FireAlarmConfigTool.Logic.Http.Client.Client.ClientUtils.ParameterToMultiMap("", "num", num));

            localVarRequestOptions.Operation = "DefaultApi.TestGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<string>("/test", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("TestGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
