/*
 * Fire Alarm Config Tool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using FireAlarmConfigTool.Logic.Api.Attributes;
using TestTest = FireAlarmConfigTool.Logic.Lib;

namespace FireAlarmConfigTool.Logic.Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    { 
        /// <summary>
        /// Test endpoint
        /// </summary>
        /// <remarks>Returns a greeting that includes the provided number.</remarks>
        /// <param name="num">A number to include in the greeting</param>
        /// <response code="200">Successful response</response>
        [HttpGet]
        [Route("/test")]
        [ValidateModelState]
        [SwaggerOperation("TestGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Successful response")]
        public virtual IActionResult TestGet([FromQuery (Name = "num")][Required()]int num)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"" + TestTest.Test.Test.testFunction(num) + "\"";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<string>(exampleJson)
            : default(string);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
